name: Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:     
  build_test_push:
    name: build_test_push
    permissions: write-all
    runs-on: ubuntu-latest 
    env:
      DOCKER_REPOSITORY: jonlimpw # name of Docker Hub ID
      IMAGE_NAME: fargatepybackend
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0   

    - name: Check code meets quality standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@v1
      with:
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_service: fargate-ecs-backend
        dd_env: ci 
        cpu_count: 2
        sca_enabled: true
        enable_performance_statistics: false

    - name: Check imported libraries are secure and compliant (DD SBOM Generate and Upload)
      id: datadog-software-composition-analysis
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_service: fargate-ecs-backend
        dd_env: ci
        dd_site: datadoghq.com
          
    - name: Build Docker Image 
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
        registry: docker.io
        tag: latest
        buildArgs: 'DD_GIT_REPOSITORY_URL=github.com/jon94/fargatepythonbackend,DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Datadog Service Catalog Metadata Provider
      uses: arcxp/datadog-service-catalog-metadata-provider@v2.1.0
      with:
        # The Datadog API hostname (this varies by Datadog customer!)
        datadog-hostname: api.datadoghq.com
        # The Datadog API key, add this as repo secret
        datadog-key: ${{secrets.DD_API_KEY}}
        # The Datadog Application key, add this as repo secret
        datadog-app-key: ${{secrets.DD_APP_KEY}}
        # The version of the Datadog Service Catalog Schema. The default is v2. Valid values are `v2` and `v2.1`.
        schema-version: v2
        # The name of the service
        service-name: fargate-python, postrequest
        # The team responsible for the service
        team: SRE
        # The email address of the team responsible for the service
        email: jonathan.lim@datadoghq.com

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version you need

    - name: Install Datadog CI dependency
      run: npm install --save-dev @datadog/datadog-ci

    - name: Set up environment variables
      run: |
        echo "DD_BETA_COMMANDS_ENABLED=1" >> $GITHUB_ENV
        echo "DD_SITE=datadoghq.com" >> $GITHUB_ENV
        echo "DD_API_KEY=${{ secrets.DD_API_KEY }}" >> $GITHUB_ENV
        
    - name: Set deploy start time
      id: deploy_start
      run: echo "deploy_start=$(date +%s)" >> $GITHUB_ENV

    - name: Set Git Commit SHA
      id: git_commit_sha
      run: echo "git_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV        

    - name: Report deployment to Datadog
      run: |
        npx datadog-ci dora deployment --service fargate-python --env fargate-ecs \
          --started-at ${{ env.deploy_start }} --finished-at $(env.date +%s) \
          --git-repository-url github.com/jon94/fargatepythonbackend \
          --git-commit-sha $(env.git_commit_sha)     

          
